### ISSUE TITLE
Problem with temporary files

### ISSUE THREAD

**Issue by gdejana** [dvitale199/GenoTools#180]
Problem temporary files

I am trying to use genotools pipeline to impute ancestry and perform qc on variants and subjects as it follows: 

`genotools --pfile /home/user/jojo/A --out /home/user/jojo/ --ref_panel /opt/tools/GenoTools/ref_panel/1kg_30x_hgdp_ashk_ref_panel --ancestry --ref_labels /opt/tools/GenoTools/ref_panel/1kg_30x_hgdp_ashk_ref_panel_labels.txt  --subset_ancestry EUR  --related True --prune_related False --prune_duplicated --all_sample True --all_variant
`
Appartly genotools stops working as it searches for file "/home/utente/jojo/A_EUR".
Should genotools search for it among temporary files?
Am I missing something?

Thank you for your time!

**Comment by dvitale199** [comment]
could you please share the error message?

**Comment by gdejana** [comment]
A was actually the name of the file, I tried to rerrun it but I end up having the same error:

`Running: callrate with input /home/utente/jojo/baustelle/filtered_CIDR_HuntingtonsDS_Top_subject_level_c1_update_MERGED_FINAL_ancestry_EUR and output: /home/utente/jojo/baustelle/.19gqojjs_tmp/res_genotools_EUR_callrate
Traceback (most recent call last):
  File "/home/utente/miniconda3/bin/genotools", line 8, in <module>
    sys.exit(handle_main())
             ^^^^^^^^^^^^^
  File "/home/utente/miniconda3/lib/python3.11/site-packages/genotools/__main__.py", line 164, in handle_main
    out_dict[label] = execute_pipeline(run_steps_list, ordered_steps, geno_path, out, samp_qc=samp_qc, var_qc=var_qc, assoc=assoc, args=args_dict, tmp_dir=tmp_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/utente/miniconda3/lib/python3.11/site-packages/genotools/pipeline.py", line 157, in execute_pipeline
    out_dict[step] = steps_dict[step](args[step])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/utente/miniconda3/lib/python3.11/site-packages/genotools/qc.py", line 64, in run_callrate_prune
    raise FileNotFoundError(f"{geno_path} does not exist.")
FileNotFoundError: /home/utente/jojo/baustelle/filtered_CIDR_HuntingtonsDS_Top_subject_level_c1_update_MERGED_FINAL_ancestry_EUR does not exist.`

Any ideas? 
I also attached the full log file:

[res_genotools_all_logs.log](https://github.com/dvitale199/GenoTools/files/15295230/res_genotools_all_logs.log)

Thank you for your time!

**Comment by dvitale199** [comment]
could you attach the "cleaned_logs" file as well?

**Comment by gdejana** [comment]
Here it is! 

Thank you again 
[res_genotools_cleaned_logs.log](https://github.com/dvitale199/GenoTools/files/15306979/res_genotools_cleaned_logs.log)
